name: Deploy Given Version
on:
  workflow_call:
    inputs:
      version_tag:
        description: "Version to deploy"
        type: string
        required: true
      lambda_name:
        description: "Lambda to Deploy"
        type: string
        required: true
      runtime_version:
        description: "runtime version to use"
        type: string
        required: true
      subdirectory:
        description: "subdirectory to deploy"
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true
permissions:
  contents: read
  id-token: write
jobs:
  go_test_package_artifact:
    name: go test package artifact
    uses: ./.github/workflows/build-go.yml
    with:
      runtime_version: ${{ inputs.runtime_version }}
      subdirectory: ${{ inputs.subdirectory }}
      lambda_name: ${{ inputs.lambda_name }}
    secrets: inherit
  deploy:
    name: Deploy (${{ inputs.version_tag }})
    needs: go_test_package_artifact
    if: ${{always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure'))}}
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      artifact_key: ${{ needs.go_test_package_artifact.outputs.artifact_key }}
      lambda_name: ${{ inputs.lambda_name }}
    secrets: inherit
