name: Build and Deploy Next.js
on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Working Directory for project'
        type: string
        default: "./nextjs"
      s3_bucket:
        description: 'S3 bucket to deploy to'
        type: string
        required: true
      cloudfront_distribution_id:
        description: 'CloudFront Distribution ID'
        type: string
        required: true
      node_version:
        description: 'Node.js version'
        type: number
        required: true
      build_directory:
        description: 'Directory of app build'
        type: string
        default: ".next"
permissions:
  contents: read
  id-token: write
jobs:
  build-and-deploy-nextjs:
    name: Build and Deploy Next.js Project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          mask-aws-account-id: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build && npm run export

      - name: Deploy to S3
        run: aws s3 sync --delete ${{ inputs.build_directory }} s3://${{ inputs.s3_bucket }}/

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ inputs.cloudfront_distribution_id }} \
            --paths "/*"
