name: Extract Referance
on:
  workflow_call:
    inputs:
      ref:
        description: "Ref to overwrite GITHUB_REF"
        type: string
    outputs:
      ref:
        description: "Fully qualified referance for the tag. Can be passed to actions/checkout workflow"
        value: ${{jobs.extract_ref.outputs.ref}}
      short_ref:
        description: "Short referance for the tag. This value matched the branch name or tag name shown on GITHUB"
        value: ${{jobs.extract_ref.outputs.short_ref}}
permissions:
  contents: read
  id-token: write
jobs:
  extract_ref:
    name: Extract Referance
    runs-on: ubuntu-latest
    outputs:
      ref: ${{steps.full_ref.outputs.ref}}
      short_ref: ${{steps.short_ref.outputs.short_ref}}
    steps:
      - id: full_ref
        name: Setup Ref Using Version Tag if Specified
        run: |
          if ${{inputs.ref =! ''}}
          then
            echo "ref=${{inputs.ref}}" >> "$GITHUB_OUTPUT"
          else
            echo "ref=${GITHUB_REF}" >> "$GITHUB_OUTPUT"
          fi
      - id: short_ref
        name: Extract Short Ref
        run: |
          echo "short_ref=${echo ${{steps.full_ref.outputs.ref}} | rev | cut -d'/' -f 1 | rev}" >> "$GITHUB_OUTPUT"
      - id: debug
        name: Debug
        run: |
          echo "ref output: ${{steps.full_ref.outputs.ref}}"
          echo "short_ref output: ${{steps.short_ref.outputs.short_ref}}"
